import {createRouter,createWebHistory} from 'vue-router';
import store from '../store';
const router=createRouter({
	history:createWebHistory(),
	routes:[
		{
			path:'/login',
			component:()=>import('../views/login/index.vue'),
			meta:{
				title:'登录'
			}
		},
		{
			path:'/home',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'',
					component:()=>import('../views/index/home.vue'),
					meta:{
						title:'首页'
					}
				}
			]
		},
		{
			path:'/auth/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'list',
					component:()=>import('../views/auth/list.vue'),
					meta:{
						title:'权限控制'
					}
				},
				{
					path:'group',
					component:()=>import('../views/auth/group.vue'),
					meta:{
						title:'用户组'
					}
				},
				{
					path:'admin',
					component:()=>import('../views/auth/admin.vue'),
					meta:{
						title:'管理员'
					}
				}
			]
		},
		{
			path:'/system/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'setlist',
					component:()=>import('../views/system/set.vue'),
					meta:{
						title:'参数管理'
					}
				},
				{
					path:'saveset',
					component:()=>import('../views/system/saveSet.vue'),
					meta:{
						title:'参数设置'
					}
				},
				{
					path:'update',
					component:()=>import('../views/system/update.vue'),
					meta:{
						title:'系统更新'
					}
				},
				{
					path:'wxMiniUpload',
					component:()=>import('../views/system/wxMiniUpload.vue'),
					meta:{
						title:'小程序上传'
					}
				},
				{
					path:'adminLog',
					component:()=>import('../views/system/adminLog.vue'),
					meta:{
						title:'管理员日志'
					}
				}
			]
		},
		{
			path:'/article/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'article',
					component:()=>import('../views/article/article.vue'),
					meta:{
						title:'文章'
					}
				},
				{
					path:'sort',
					component:()=>import('../views/article/sort.vue'),
					meta:{
						title:'文章分类'
					}
				}
			]
		},
		{
			path:'/gallery/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'index',
					component:()=>import('../views/gallery/index.vue'),
					meta:{
						title:'图片列表'
					}
				},
				{
					path:'sort',
					component:()=>import('../views/gallery/sort.vue'),
					meta:{
						title:'图片分类'
					}
				}
			]
		},
		{
			path:'/user/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'index',
					component:()=>import('../views/user/index.vue'),
					meta:{
						title:'用户列表'
					}
				},
				{
					path:'tg',
					component:()=>import('../views/user/tg.vue'),
					meta:{
						title:'高级推广'
					}
				},
				{
					path:'cash',
					component:()=>import('../views/cash/index.vue'),
					meta:{
						title:'提现列表'
					}
				},
				{
					path:'balance',
					component:()=>import('../views/user/balance.vue'),
					meta:{
						title:'余额明细'
					}
				},
				{
					path:'goodsList',
					component:()=>import('../views/user/userGoods.vue'),
					meta:{
						title:'商品获取记录'
					}
				}
			]
		},
		{
			path:'/goods/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'index',
					component:()=>import('../views/goods/index.vue'),
					meta:{
						title:'商品列表'
					}
				},
				{
					path:'sort',
					component:()=>import('../views/goods/sort.vue'),
					meta:{
						title:'商品分类'
					}
				},
				{
				    path:'column',
					component:()=>import('../views/goods/column.vue'),
					meta:{
						title:'商品栏目'
					}
				},
				{
					path:'task',
					component:()=>import('../views/goods/task.vue'),
					meta:{
						title:'任务列表'
					}
				}
			]
		},
		{
		    path:'/theme/',
		    component:()=>import('../views/index/index.vue'),
		    children:[
		        {
		            path:'index',
		            component:()=>import('../views/theme/index.vue'),
		            meta:{
		                title:'首页装修'
		            }
		        },
				{
		            path:'vip',
		            component:()=>import('../views/theme/vip.vue'),
		            meta:{
		                title:'会员装修'
		            }
		        },
				{
		            path:'tabBar',
		            component:()=>import('../views/theme/tabBar.vue'),
		            meta:{
		                title:'导航装修'
		            }
				},
				{
		            path:'user',
		            component:()=>import('../views/theme/user.vue'),
		            meta:{
		                title:'个人中心'
		            }
				},
				{
		            path:'promotion',
		            component:()=>import('../views/theme/promotion.vue'),
		            meta:{
		                title:'推广装修'
		            }
				},
				{
		            path:'pages',
		            component:()=>import('../views/theme/pages.vue'),
		            meta:{
		                title:'页面连接'
		            }
				},
				{
		            path:'sort',
		            component:()=>import('../views/theme/sort.vue'),
		            meta:{
		                title:'分类装修'
		            }
				}
			]
		},
		{
			path:'/vip/',
			component:()=>import('../views/index/index.vue'),
		    children:[
		        {
		            path:'index',
		            component:()=>import('../views/vip/index.vue'),
		            meta:{
		                title:'会员列表'
		            }
		        },
				{
		            path:'privilege',
		            component:()=>import('../views/vip/privilege.vue'),
		            meta:{
		                title:'会员特权'
		            }
		        }
			]
		},
		{
			path:'/kami/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'index',
					component:()=>import('../views/kami/index.vue'),
					meta:{
						title:'卡密列表'
					}
				}				
			]
		},
		{
			path:'/order/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'index',
					component:()=>import('../views/order/index.vue'),
					meta:{
						title:'订单列表'
					}
				}
			]
		},
		{
			path:'/points/',
			component:()=>import('../views/index/index.vue'),
			children:[
				{
					path:'sign',
					component:()=>import('../views/points/sign.vue'),
					meta:{
						title:'签到设置'
					}
				},
				{
					path:'log',
					component:()=>import('../views/points/log.vue'),
					meta:{
						title:'积分明细'
					}
				}
			]
		}
	]
});
router.beforeEach((to, from) => { //前置守卫
	let user=localStorage.getItem('user')
	if(!user && to.path!='/login'){
		return '/login';
	}
	if(to.path=='/'){	
		let tableTabsValue=Number(localStorage.getItem('tableTabsValue'));
		if(tableTabsValue){		
			let tableTabs=JSON.parse(localStorage.getItem('tableTabs'));
			let index = tableTabs.findIndex(val => val.name==tableTabsValue);
			if(index>=0){
				return tableTabs[index].path
			}else{
				return '/home'
			}
		}else{
			return '/home'
		}		
	}
});
router.afterEach((to, from) => { //后置守卫
	if(to.meta.title){
		document.title=to.meta.title;
	}
});
export default router;
